In [1]:
import numpy as np
i=np.array([10,20,30,40,50,60])
print(i[0])

10


In [5]:
import numpy as np
i=np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
print(i[1,1])

70


In [6]:
import numpy as np
i = np.array([
[10,20,30,40,50],
[60,70,80,90,100]
])
print(i[0, 4])

50


In [10]:
import numpy as np
i=np.array([
    [[10,20,30,40],[50,60,40,30]],
    [[40,50,60,80],[90,80,50,60]]
    
])
print(i[0,1,2])

40


In [13]:
import numpy as np
arr = np.array([
 [[10, 20, 30], [40, 50, 60]], 
 [[70, 80, 90], [100, 110, 120]] 
 ]) 
print(arr[1, 1, 2])

120


In [15]:
import numpy as np
arr = np.array([
 [[10, 20, 30], [40, 50, 60]], 
 [[70, 80, 90], [100, 110, 120]] 
 ])
print(arr[1, 1, -1])

120


In [16]:
 import numpy as np
arr = np.array([
 [[10, 20, 30], [40, 50, 60]], 
 [[70, 80, 90], [100, 110, 120]] 
 ])
print(arr[1, -2, -1])

90


In [17]:
import numpy as np
i=np.array([10,20,30,40,60])
print(i[-1])

60


In [3]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[0:3])

[10 20 30]


In [5]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[3:6])

[40 50 60]


In [6]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[2:])

[30 40 50 60 70 80]


In [7]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[ : 6])

[10 20 30 40 50 60]


In [8]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[-5 :-2])

[40 50 60]
